server:
  port: 8800
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

#    url: jdbc:mariadb://192.168.0.114:3306/semes_db
#    username: root
#    password: password
    #정호 로컬 집
    url: jdbc:mariadb://localhost:3306/blog_db?serveTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true